
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOADER = "LOADER";
export const ACTIVE = "ACTIVE";
export const USER_DATA = "USER_DATA";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CLIENTS = "GET_CLIENTS";
export const SET_SCHEDULECOUNT = "SET_SCHEDULECOUNT";
export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";
export const SET_COLOR = "SET_COLOR";
export const SET_PRIMRY_COLOR = "SET_PRIMRY_COLOR";





// Chat Action Types
export const SET_CHATS = "SET_CHATS";
export const CLEAR_CHATS = "CLEAR_CHATS";
export const UPDATE_CHATS = "UPDATE_CHATS";
export const APPEND_CHATS = "APPEND_CHATS";
export const CHAT_COUNT = "CHAT_COUNT";
export const CLIENT_MSG_COUNT = "CLIENT_MSG_COUNT";
export const USER_MSG_COUNT = "USER_MSG_COUNT";
export const SEEN_USER_MSG_COUNT = "SEEN_USER_MSG_COUNT";
export const SEEN_CLIENT_MSG_COUNT = "SEEN_CLIENT_MSG_COUNT";
export const REMOVE_CLIENT_MSG_COUNT = "REMOVE_CLIENT_MSG_COUNT";
export const REMOVE_USER_MSG_COUNT = "REMOVE_USER_MSG_COUNT";
export const UPDATE_CLIENT_MSG_COUNT = "UPDATE_CLIENT_MSG_COUNT";
export const UPDATE_USER_MSG_COUNT = "UPDATE_USER_MSG_COUNT";
export const SET_USER_LAST_MESSAGE = "SET_USER_LAST_MESSAGE";
export const SET_CLIENT_LAST_MESSAGE = "SET_CLIENT_LAST_MESSAGE";



//Job Action Types
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REPLACE_CART = "REPLACE_CART";
export const UPDATE_PRODUCT_QUANTITY = "UPDATE_PRODUCT_QUANTITY";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const UPDATE_TITLE = "UPDATE_TITLE";
export const UPDATE_MANUAL_DISCOUNT = "UPDATE_MANUAL_DISCOUNT";
export const UPDATE_DEPOSIT = "UPDATE_DEPOSIT";
export const LOAD_JOB = "LOAD_JOB";
export const LOAD_JOB_OBJ = "LOAD_JOB_OBJ";
export const CLEAR_JOB = "CLEAR_JOB";
export const UPDATE_JOBID = "UPDATE_JOBID";
export const LOAD_QUOTE = "LOAD_QUOTE";
export const LOAD_QUOTE_OBJ = "LOAD_QUOTE_OBJ";
export const CLEAR_QUOTE = "CLEAR_QUOTE";
